apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default  # Add the namespace here
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

