apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs-app
  template:
    metadata:
      labels:
        app: reactjs-app
    spec:
      containers:
      - name: reactjs
        image: your-dockerhub-username/reactjs-app:latest # Replace with your Docker image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  selector:
    app: reactjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

